version: "3.4"
services:
  app:
    image: tomatentim/freegames-notifier
    restart: unless-stopped
    environment:
      - DISCORD_WEBHOOKS=<discord webhooks comma separated>
    volumes:
      - data:/app/data

volumes:
  data: